@baseURL = http://localhost:80/user
# @baseURL = https://server-dnp.onrender.com/user
###
# GET All User
GET {{baseURL}}

###
# GET User by Id
GET {{baseURL}}/1

###
# POST User
POST {{baseURL}} HTTP/1.1
content-type: application/json

{
    "name": "Juan",
    "surname": "Mansilla",
    "email": "juan123@mansilla.com",
    "dob": 123456789,
    "password": "@Juan123"
}

###
# DELETE User by Id
DELETE {{baseURL}}/1

###
# GET Login User
POST {{baseURL}}/login HTTP/1.1
content-type: application/json

{
    "email": "juan@mansilla.com",
    "password": "@Juan123"
}
###